# Makefile for include files

FILES.h = bisp.h \
          boundary.h \
          file_cat_out.h \
          file_handle.h \
          file_path.h \
          files_in.h \
          files_out.h \
          geo_values.h \
          grid.h \
          m_values.h \
          mem_er.h \
          netcdf_info.h \
          pp.h \
          proj.h \
          periodogram.h \
          p_vecs.h \
          region.h \
          splice.h \
          sqt.h \
          st_fo.h \
          st_im.h \
          st_obj.h \
          st_track.h \
          statistic.h \
          tele.h \
          tessel.h \
          threshold.h \
          utf.h \
          zones.h \
          Math.h \
          Stdio.h 



all: $(FILES.h) 

.KEEP_STATE:
