SOURCES=read_tracks.c \
        toverlap.c \
        measure.c \
        euclid.c \
        geod_dist.c \
        malloc_initl.c \
        meantrd.c \
        realloc_n.c \
        new_time.c


OBJECTS=$(SOURCES:.c=.o)

#CFLAGS = -g -Xa -xsb -I../../include

CFLAGS = -g -ansi -Wall -I../../include -D${SYSTEM} $(AD_C_FLAGS)

#LIBS = -lm -lsunmath
LIBS = -lm


.KEEP_STATE:

all: censemble2 eps ensdiff homogenize replace replace_wind



#censemble: $(OBJECTS) compare_ensemble.c trdist.c
#	$(CC) $(CFLAGS) -c compare_ensemble.c trdist.c
#	$(CC) $(CFLAGS) -o ../bin/$@ $(OBJECTS) compare_ensemble.o trdist.o $(LIBS)

censemble2: $(OBJECTS) compare_ensemble2.c trdist.c
	$(CC) $(CFLAGS) -c compare_ensemble2.c trdist.c
	$(CC) $(CFLAGS) -o ../bin/$@ $(OBJECTS) compare_ensemble2.o trdist.o $(LIBS)

eps: $(OBJECTS) eps_ensemble.c trdist_eps.c convert_track.c ortho_dist.c sincos.c
	$(CC) $(CFLAGS) -c eps_ensemble.c trdist_eps.c convert_track.c ortho_dist.c sincos.c
	$(CC) $(CFLAGS) -o ../bin/$@ $(OBJECTS) eps_ensemble.o trdist_eps.o convert_track.o ortho_dist.o sincos.o $(LIBS)

ensdiff: $(OBJECTS) ensdiff.c convert_track.c ortho_dist.c sincos.c
	$(CC) $(CFLAGS) -c ensdiff.c convert_track.c ortho_dist.c sincos.c
	$(CC) $(CFLAGS) -o ../bin/$@ $(OBJECTS) ensdiff.o convert_track.o ortho_dist.o sincos.o $(LIBS)
	
homogenize: homogenize.c read_tracks.o meantrd.o toverlap.o
	$(CC) $(CFLAGS) -c homogenize.c
	$(CC) $(CFLAGS) -o ../bin/$@ homogenize.o read_tracks.o meantrd.o toverlap.o $(LIBS)
	
replace: replace.c read_tracks.o meantrd.o toverlap.o
	$(CC) $(CFLAGS) -c replace.c
	$(CC) $(CFLAGS) -o ../bin/$@ replace.o read_tracks.o meantrd.o toverlap.o $(LIBS)
	
replace_wind: replace_wind.c read_tracks.o meantrd.o toverlap.o
	$(CC) $(CFLAGS) -c replace_wind.c
	$(CC) $(CFLAGS) -o ../bin/$@ replace_wind.o read_tracks.o meantrd.o toverlap.o $(LIBS)
